DDT-1136
dcsaorg/DCSA-JIT pull request #142
Opened 2022-07-21 12:09 UTC by FinnAtAsseco

2022-07-21 15:08 UTC, FinnAtAsseco commented on jit-service/src/main/java/org/dcsa/jit/mapping/TransportCallMapper.java
> +        @Mapping(target = "carrierExportVoyageNumber", source = "exportVoyage.carrierVoyageNumber"),
I thought the idea was to allow jit 1.1 input, but always return jit 1.2

2022-07-22 07:43 UTC, FinnAtAsseco commented on jit-service/src/main/java/org/dcsa/jit/mapping/TransportCallMapper.java
> +        @Mapping(target = "carrierExportVoyageNumber", source = "exportVoyage.carrierVoyageNumber"),
Fixed, will now map both

2022-07-25 07:41 UTC, Abdiiir commented on jit-integration-tests/src/main/java/org/dcsa/jit/itests/v1/PostTimestampsIT.java
> +    map.remove("carrierExportVoyageNumber");
This is still a valid timestamp1_1 (line 727), so nothing is being removed in the map. 

I think we should keep this test, as part of backwards comp for JIT 1.1

2022-07-25 08:02 UTC, Abdiiir requested changes

2022-07-25 08:02 UTC, Abdiiir commented on jit-integration-tests/src/main/java/org/dcsa/jit/itests/v1/PostTimestampsIT.java
>    public void testLogicForVoyageNumberFields() {
New test should be added, instead of changing this one.

2022-07-25 13:26 UTC, Abdiiir commented on jit-transfer-obj/src/main/java/org/dcsa/jit/transferobjects/TimestampTO.java
> +  @Deprecated @NotNull @ValidVesselIMONumber String vesselIMONumber, // Deprecated in JIT 1.2
No need since, @ValidVesselIMONumber also checks for null.

2022-07-25 13:50 UTC, Abdiiir submitted a review, later dismissed

2022-07-26 08:11 UTC, douradofrazer approved these changes

2022-07-26 08:12 UTC, merged