Migrate to Shared-Kernel v0.2.0
dcsaorg/DCSA-JIT pull request #191
Opened 2022-11-24 13:02 UTC by nt-as

2022-11-25 14:28 UTC, douradofrazer requested changes

2022-11-25 14:28 UTC, douradofrazer commented on jit-application/src/main/java/org/dcsa/jit/Application.java
> +@EnableJpaRepositories("org.dcsa")
Might be good to move the scans to a configuration class, as we do in the other projects.

2022-11-25 14:36 UTC, FinnAtAsseco commented on jit-application/src/test/java/org/dcsa/jit/datafactories/OperationsEventTODataFactory.java
> +        LocationTO.UNLocationLocationTO.builder()
(Optional) Use the shortcuts LocationTO.unLocationLocationBuilder()

2022-11-28 11:33 UTC, douradofrazer approved these changes

2022-11-28 11:33 UTC, merged

2022-11-28 11:58 UTC, Abdiiir approved these changes