DDT-1337: Added timestampID to TimestampTO
dcsaorg/DCSA-JIT pull request #195
Opened 2022-11-28 13:34 UTC by Abdiiir

- Added test for duplicate timestampID

2022-11-28 13:35 UTC, nt-as commented on jit-persistence/src/main/java/org/dcsa/jit/persistence/entity/OperationsEvent.java
> +    return this.newRecord;
```suggestion
    return eventID != null || this.newRecord;
```

2022-11-28 13:36 UTC, nt-as commented
(also has a test failure)

2022-11-28 13:39 UTC, Abdiiir commented on jit-persistence/src/main/java/org/dcsa/jit/persistence/entity/OperationsEvent.java
> +    return this.newRecord;
will amend commit.

2022-12-01 10:03 UTC, nt-as requested changes
Please update the postman collection to post the same timestamp twice with the same ID (so it does not depend on operations event from SQL).

2022-12-05 10:20 UTC, nt-gt approved these changes

2022-12-05 10:24 UTC, merged